version: '3.9'

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: zidallie-backend-postgres-1
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: zidallie-redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zidallie-backend-api
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - backend

volumes:
  postgres_data:
  redisdata:

networks:
  backend:
    driver: bridge
